# Code generated by kickr; DO NOT EDIT.

TFLINT_PATH ?= .tflint.hcl

.PHONY: fmt
fmt:
	@tofu fmt -diff -recursive

.PHONY: tflint
tflint:
	@tflint --config "${TFLINT_PATH}" --recursive --format compact $(ARGS) || \
		echo "tflint failed, running 'make tflint-fix' may fix some issues"

.PHONY: tflint-fix
tflint-fix:
	@ARGS="--fix" make -s tflint
