# Code generated by kickr; DO NOT EDIT.

APP_VERSION ?= v0.0.0

.PHONY: build
build:
	@hugo --gc --minify --destination dist --logLevel debug

.PHONY: serve
serve:
	@hugo server --disableFastRender --destination dist --logLevel debug

.PHONY: production
production: build
	@python3 -m http.server --directory dist

.PHONY: docker
docker:
	@docker build . \
		-f Dockerfile \
		-t kickr:${APP_VERSION} \
		--build-arg GIT_REF_NAME=$(shell git rev-parse --abbrev-ref HEAD) \
		--build-arg GIT_COMMIT=$(shell git rev-parse HEAD) \
		--build-arg APP_VERSION=${APP_VERSION}
