# Code generated by kickr; DO NOT EDIT.

.PHONY: clean
clean:
	@git clean -dfX

.PHONY: build-docs
build-docs:
	@hugo --gc --minify --destination dist --logLevel debug --source docs

.PHONY: serve-docs
serve-docs:
	@hugo server --disableFastRender --destination dist --logLevel debug --source docs

.PHONY: production-docs
production-docs: build-docs
	@python3 -m http.server --directory dist
