# Code generated by kickr; DO NOT EDIT.

# Each submodule is driven through its own Makefile, i.e. 'make docs-build' runs 'build' in the docs module.
# Available targets depend on the languages of the submodule, see its own scripts/mk directory.

docs-%:
	@$(MAKE) -C docs $*

website-%:
	@$(MAKE) -C website $*
