// Code generated by AI (Claude Opus 4.5).

package kickr

const (
	EnvironmentIntegration = "integration"
	EnvironmentProduction  = "production"
	EnvironmentReview      = "review"
	EnvironmentStaging     = "staging"
)

const (
	ExcludeGoreleaser = "goreleaser"
	ExcludeMakefile   = "makefile"
	ExcludePreCommit  = "pre-commit"
	ExcludeRenovate   = "renovate"
	ExcludeShell      = "shell"
)

const (
	HelmDeployAuto   = "auto"
	HelmDeployManual = "manual"
)

const (
	HelmPublishAuto   = "auto"
	HelmPublishManual = "manual"
)

const (
	LicenseAGPL30     = "agpl-3.0"
	LicenseApache20   = "apache-2.0"
	LicenseBSD2Clause = "bsd-2-clause"
	LicenseBSD3Clause = "bsd-3-clause"
	LicenseBSL10      = "bsl-1.0"
	LicenseCC010      = "cc0-1.0"
	LicenseEPL20      = "epl-2.0"
	LicenseGPL20      = "gpl-2.0"
	LicenseGPL30      = "gpl-3.0"
	LicenseLGPL21     = "lgpl-2.1"
	LicenseMIT        = "mit"
	LicenseMPL20      = "mpl-2.0"
	LicenseUnlicense  = "unlicense"
)

const (
	OptionsCodecov               = "codecov"
	OptionsCodeQL                = "codeql"
	OptionsHardenRunner          = "harden-runner"
	OptionsKickr                 = "kickr"
	OptionsKickrGitHubApp        = "kickr:github-app"
	OptionsKickrPersonalToken    = "kickr:personal-token"
	OptionsLabeler               = "labeler"
	OptionsOSSFScorecard         = "ossf-scorecard"
	OptionsRenovate              = "renovate"
	OptionsRenovateGitHubApp     = "renovate:github-app"
	OptionsRenovatePersonalToken = "renovate:personal-token"
	OptionsSonarQube             = "sonarqube"
	OptionsStepSecurityActions   = "step-security-actions"
)

const (
	PlatformBitbucket = "bitbucket"
	PlatformGitea     = "gitea"
	PlatformGitHub    = "github"
	PlatformGitLab    = "gitlab"
)

const (
	PreCommitAutoCommit          = "auto-commit"
	PreCommitConventionalCommits = "conventional-commits"
	PreCommitGitflowBranches     = "gitflow-branches"
	PreCommitGolangciLint        = "golangci-lint"
	PreCommitGomodTidy           = "gomod-tidy"
	PreCommitTerraform           = "terraform"
)

const (
	ProviderGitHub = "github"
	ProviderGitLab = "gitlab"
)

const (
	ReleaseAuthGitHubApp     = "github-app"
	ReleaseAuthGitHubToken   = "github-token"
	ReleaseAuthPersonalToken = "personal-token"
)

const (
	ReleaseOptionsBackmerge = "backmerge"
)

const (
	TerraformApplyAuto   = "auto"
	TerraformApplyManual = "manual"
)

const (
	TerraformEngineOpenTofu  = "opentofu"
	TerraformEngineTerraform = "terraform"
)

const (
	WebsiteHostingNetlify = "netlify"
	WebsiteHostingPages   = "pages"
)
