// Code generated by AI (Claude Opus 5).

package kickr

// Kickr represents the Kickr configuration file.
type Kickr struct {
	// Version defines the Kickr schema version.
	Version int `json:"version,omitempty" yaml:"version,omitempty"`

	// Description is a free-form text that may be used in various cases like in the Helm chart, the Dockerfile, etc.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`

	// Docker defines the general Docker configuration.
	Docker *Docker `json:"docker,omitempty" yaml:"docker,omitempty"`

	// Exclude defines the part of Kickr generation to exclude.
	//
	// Enums:
	//  - code-of-conduct
	//  - makefile
	//  - pre-commit
	//  - renovate
	//  - shell
	Exclude []string `json:"exclude,omitempty" yaml:"exclude,omitempty"`

	// GitHub enables GitHub Actions with options to tune behaviors.
	GitHub *GitHub `json:"github,omitempty" yaml:"github,omitempty"`

	// GitLab enables GitLab CICD with options to tune behaviors.
	GitLab *GitLab `json:"gitlab,omitempty" yaml:"gitlab,omitempty"`

	// Helm defines the general Helm configuration.
	Helm *Helm `json:"helm,omitempty" yaml:"helm,omitempty"`

	// License specifies the repository license.
	//
	// Enums:
	//  - agpl-3.0
	//  - apache-2.0
	//  - bsd-2-clause
	//  - bsd-3-clause
	//  - bsl-1.0
	//  - cc0-1.0
	//  - epl-2.0
	//  - gpl-2.0
	//  - gpl-3.0
	//  - lgpl-2.1
	//  - mit
	//  - mpl-2.0
	//  - unlicense
	License string `json:"license,omitempty" yaml:"license,omitempty"`

	// Maintainers defines the repository's maintainers list.
	Maintainers []*Maintainer `json:"maintainers,omitempty" yaml:"maintainers,omitempty"`

	// Modules defines the directories the repository is made of, each one owning its own technology stack.
	//
	// When absent or empty, the repository root is the sole module.
	// Otherwise every module must be declared, the repository root included as '.'.
	Modules []Module `json:"modules,omitempty" yaml:"modules,omitempty"`

	// Platform defines the source code hosting platform (GitHub, GitLab, Gitea, Bitbucket).
	//
	// By default, it will be guessed based on Git remote URL.
	// However, in case of mirroring, or other specific cases (like custom hosting), it may be updated to provide a custom platform.
	//
	// Helps generating various files the badges in README.md.
	//
	// Enums:
	//  - bitbucket
	//  - gitea
	//  - github
	//  - gitlab
	Platform string `json:"platform,omitempty" yaml:"platform,omitempty"`

	// PreCommit section can be provided to add additional, non-default, checks with pre-commit.
	//
	// All options available here are implemented in Kickr templates, there's no possibly to directly give pre-commit hooks definition.
	//
	// In case a specific hook, not implemented, must be provided, then '.pre-commit-config.yaml' file can be modified
	// and the top comment indicating that it's generated can be removed to avoid being overridden.
	//
	// Enums:
	//  - auto-commit
	//  - conventional-commits
	//  - gitflow-branches
	//  - golangci-lint
	//  - gomod-tidy
	//  - terraform
	PreCommit []string `json:"pre-commit,omitempty" yaml:"pre-commit,omitempty"`
}

// Module represents one directory of the repository, owning its own technology stack.
//
// Languages are detected by kickr inside the directory, they aren't configured here.
//
// With 'ci' enabled, control where the module is deployed and, for terraform modules,
// when shall they be applied and on which environments.
type Module struct {
	// Path defines the module location, relative to the repository root.
	//
	// Examples:
	//  - .
	//  - docs
	//  - apps/api
	Path string `json:"path,omitempty" yaml:"path,omitempty"`

	// Exclude defines available options to remove from this module generation.
	//
	// Enums:
	//  - docker
	//  - makefile
	Exclude []string `json:"exclude,omitempty" yaml:"exclude,omitempty"`

	// Deployment defines where and how the module is deployed.
	Deployment *Deployment `json:"deployment,omitempty" yaml:"deployment,omitempty"`

	// Terraform defines the module as a terraform one, alongside its engine and apply strategy.
	Terraform *Terraform `json:"terraform,omitempty" yaml:"terraform,omitempty"`
}

// Deployment defines where and how a module is deployed.
type Deployment struct {
	// Auto defines whether the module shall be deployed automatically (or not) on its target.
	Auto bool `json:"auto,omitempty" yaml:"auto,omitempty"`

	// Target defines the deployment target of the module.
	//
	// 'netlify' and 'pages' build and publish the module as a static website.
	// 'helm' includes the module executables in the generated Helm Chart values.
	//
	// Enums:
	//  - helm
	//  - netlify
	//  - pages
	Target string `json:"target,omitempty" yaml:"target,omitempty"`
}

// Terraform configures the terraform module and the engine to use (tofu by default).
//
// With 'ci' enabled, control when shall the terraform modules be applied (or not) and on which environments.
type Terraform struct {
	// Apply defines the apply strategy.
	//
	// Not providing this property will mean 'never' as strategy, no apply job will be generated.
	//
	// Enums:
	//  - auto
	//  - manual
	Apply string `json:"apply,omitempty" yaml:"apply,omitempty"`

	// Engine defines the engine to use to lint, validate, test, apply the resources.
	//
	// Enums:
	//  - tofu
	//  - terraform
	Engine string `json:"engine,omitempty" yaml:"engine,omitempty"`

	// Environments defines the environments to associate a specific apply with.
	//
	// Enums:
	//  - integration
	//  - production
	//  - review
	//  - staging
	Environments []string `json:"environments,omitempty" yaml:"environments,omitempty"`
}

// Docker defines the general Docker configuration.
//
// With 'ci' enabled, control where (registry and path) shall the built Docker image be pushed and when (automatically or not).
type Docker struct {
	// Auto defines the Docker push strategy (automatic or not).
	Auto bool `json:"auto,omitempty" yaml:"auto,omitempty"`

	// Path defines the Docker image path inside the registry (default is the path on VCS remote URL).
	//
	// Examples:
	//  - kickr-dev/kickr
	Path string `json:"path,omitempty" yaml:"path,omitempty"`

	// Port defines the port to expose in the Dockerfile.
	//
	// Examples:
	//  - 3000
	Port int `json:"port,omitempty" yaml:"port,omitempty"`

	// Registry defines the Docker registry where the image will be pushed.
	//
	// By default it's the current VCS registry, i.e. 'ghcr.io' when working with GitHub
	// and 'registry.gitlab.com' when working with GitLab.
	//
	// Examples:
	//  - docker.io
	//  - ghcr.io
	//  - registry.gitlab.com
	Registry string `json:"registry,omitempty" yaml:"registry,omitempty"`
}

// GitHub enables GitHub Actions with options to tune behaviors.
type GitHub struct {
	// Exclude defines available options to remove from GitHub Actions generation.
	//
	// Enums:
	//  - pre-commit
	Exclude []string `json:"exclude,omitempty" yaml:"exclude,omitempty"`

	// Options defines available options to tune GitHub Actions.
	//
	// Enums:
	//  - codecov
	//  - codeql
	//  - harden-runner
	//  - kickr:github-app
	//  - kickr:personal-token
	//  - labeler
	//  - ossf-scorecard
	//  - renovate:github-app
	//  - renovate:personal-token
	//  - sonarqube
	//  - step-security-actions
	Options []string `json:"options,omitempty" yaml:"options,omitempty"`

	// Release tunes various configuration on the releasing part.
	Release *Release `json:"release,omitempty" yaml:"release,omitempty"`
}

// GitLab enables GitLab CICD with options to tune behaviors.
type GitLab struct {
	// Exclude defines available options to remove from GitLab CICD generation.
	//
	// Enums:
	//  - pre-commit
	Exclude []string `json:"exclude,omitempty" yaml:"exclude,omitempty"`

	// Options defines available options to tune GitLab CICD jobs.
	//
	// Enums:
	//  - kickr
	//  - overrides:deployment
	//  - overrides:integration
	//  - renovate
	//  - sonarqube
	Options []string `json:"options,omitempty" yaml:"options,omitempty"`

	// Release tunes various configuration on the releasing part.
	Release *Release `json:"release,omitempty" yaml:"release,omitempty"`
}

// Helm defines the general Helm configuration.
//
// With 'ci' enabled, control how and when shall the Helm Chart be published or deployed alongside on which environments.
type Helm struct {
	// Deploy defines the Helm Chart deployment strategy (automatic or manual).
	//
	// Not providing this property will mean 'never' as strategy, no deployment job will be generated.
	//
	// Enums:
	//  - auto
	//  - manual
	Deploy string `json:"deploy,omitempty" yaml:"deploy,omitempty"`

	// Environments to associate a specific Kubernetes context to a branch.
	//
	// Only those four environments can be provided, defining under the hood specific behaviors (for GitHub Actions):
	//   - 'review' will only be run on non-protected branches
	//   - 'integration' will only be run on protected
	//   - 'staging' will only be run on the default branch
	//   - 'production' will only be run on the default branch
	//
	// Concerning GitLab CI/CD, rules can be found at https://gitlab.com/to-be-continuous/helm#managed-deployment-environments.
	//
	// Enums:
	//  - integration
	//  - production
	//  - review
	//  - staging
	Environments []string `json:"environments,omitempty" yaml:"environments,omitempty"`

	// Path within the helm registry (default is the path on VCS remote URL).
	//
	// Examples:
	//  - kickr-dev/kickr
	Path string `json:"path,omitempty" yaml:"path,omitempty"`

	// Publish defines the Helm Chart publishing strategy.
	//
	// Not providing this property will mean 'never' as strategy, no publish job will be generated.
	//
	// Enums:
	//  - auto
	//  - manual
	Publish string `json:"publish,omitempty" yaml:"publish,omitempty"`

	// Registry URL (both OCI and non-OCI based registry are supported).
	//
	// Depending on the project registry (GitHub, Jfrog, Nexus, etc.), this property may need a more specific path like 'oci://jfrog.example.com/my/registry'.
	//
	// Examples:
	//  - ghcr.io
	//  - oci://ghcr.io
	Registry string `json:"registry,omitempty" yaml:"registry,omitempty"`
}

// Maintainer defines a project maintainer.
type Maintainer struct {
	// Email defines the maintainer email.
	//
	// Examples:
	//  - maintainer@example.com
	Email string `json:"email,omitempty" yaml:"email,omitempty"`

	// Name defines the maintainer name or username.
	//
	// Examples:
	//  - maintainer
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// URL defines the maintainer personal portfolio / URL.
	//
	// Examples:
	//  - maintainer.example.com
	URL string `json:"url,omitempty" yaml:"url,omitempty"`
}

// Release tunes various configuration on the releasing part.
//
// From automatic releasing to how the authentication should be made with which semantic-release plugins.
type Release struct {
	// Auth defines the authentication method to create releases through the current VCS platform API.
	//
	// Enums:
	//  - github-app
	//  - github-token
	//  - personal-token
	Auth string `json:"auth,omitempty" yaml:"auth,omitempty"`

	// Auto defines whether the release job should be executed automatically (or not).
	Auto bool `json:"auto,omitempty" yaml:"auto,omitempty"`

	// Options to add in release job / release configuration.
	//
	// Enums:
	//  - backmerge
	Options []string `json:"options,omitempty" yaml:"options,omitempty"`
}
