# Kickr configuration file (https://github.com/kickr-dev/kickr)
# yaml-language-server: $schema=.schemas/kickr.v1.schema.json
version: 1
exclude:
  - shell
gitlab:
  options:
    - kickr
  release: {}
license: apache-2.0
maintainers:
  - name: u.kilianpaquier
platform: gitlab
pre-commit:
  - conventional-commits
