# Code generated by kickr; DO NOT EDIT.

#############################
#        STAGE BUILD        #
#############################
FROM golang:1.25.2 AS build

ARG CGO_ENABLED=0
ARG GIT_REF_NAME
ARG GIT_COMMIT
ARG VERSION=v0.0.0

WORKDIR /app

COPY . .

RUN go mod download && \
    CGO_ENABLED=$CGO_ENABLED go build \
        -ldflags "\
            -X 'github.com/kickr-dev/kickr/internal/build.branch=$GIT_REF_NAME' \
            -X 'github.com/kickr-dev/kickr/internal/build.commit=$GIT_COMMIT' \
            -X 'github.com/kickr-dev/kickr/internal/build.date=$(TZ="UTC" date '+%Y-%m-%dT%TZ')' \
            -X 'github.com/kickr-dev/kickr/internal/build.version=$VERSION' \
        " \
        -o kickr ./cmd/kickr

#############################
#         STAGE RUN         #
#############################
FROM gcr.io/distroless/static-debian12:nonroot

LABEL org.opencontainers.image.authors="kilianpaquier"
LABEL org.opencontainers.image.vendor="kilianpaquier"

LABEL org.opencontainers.image.title="kickr"
LABEL org.opencontainers.image.licenses="APACHE-2.0"
LABEL org.opencontainers.image.url="github.com/kickr-dev/kickr"
LABEL org.opencontainers.image.source="github.com/kickr-dev/kickr"
LABEL org.opencontainers.image.documentation="github.com/kickr-dev/kickr"

WORKDIR /app

COPY --from=build \
    /app/kickr \
    ./

EXPOSE 3000

ENTRYPOINT [ "/app/kickr" ]
