{{- define "golang" }}

{{- $specifics := get .Languages "go" }}

{{- $binaries := dict }}
{{- $_ := map $binaries .Clis .Crons .Jobs .Workers }}

{{- $maintainer := index .Maintainers 0 }}

#############################
#        STAGE BUILD        #
#############################
FROM golang:{{ $specifics.Toolchain | default $specifics.Go }} AS build

ARG CGO_ENABLED=0
ARG GIT_REF_NAME
ARG GIT_COMMIT
ARG APP_VERSION=v0.0.0

WORKDIR /app

COPY . .

RUN go mod download{{ range $name, $config := $binaries }} && \
    CGO_ENABLED=$CGO_ENABLED go build \
        -ldflags "\
            -X '{{ $specifics.Module }}/internal/build.branch=$GIT_REF_NAME' \
            -X '{{ $specifics.Module }}/internal/build.commit=$GIT_COMMIT' \
            -X '{{ $specifics.Module }}/internal/build.date=$(TZ="UTC" date '+%Y-%m-%dT%TZ')' \
            -X '{{ $specifics.Module }}/internal/build.version=$APP_VERSION' \
        " \
        -o {{ $name }} ./cmd/{{ $name }}
{{- end }}

#############################
#         STAGE RUN         #
#############################
FROM gcr.io/distroless/static-debian12:nonroot

LABEL org.opencontainers.image.authors="{{ $maintainer.Name }}{{ if $maintainer.Email }} <{{ $maintainer.Email }}>{{ end }}"
LABEL org.opencontainers.image.vendor="{{ $maintainer.Name }}"

LABEL org.opencontainers.image.title="{{ .VCS.ProjectName }}"
{{- if .Description }}
LABEL org.opencontainers.image.description="{{ .Description }}"
{{- end }}
{{- if .License }}
LABEL org.opencontainers.image.licenses="{{ upper .License }}"
{{- end }}
LABEL org.opencontainers.image.url="{{ print .VCS.ProjectHost "/" .VCS.ProjectPath }}"
LABEL org.opencontainers.image.source="{{ print .VCS.ProjectHost "/" .VCS.ProjectPath }}"
LABEL org.opencontainers.image.documentation="{{ print .VCS.ProjectHost "/" .VCS.ProjectPath }}"

WORKDIR /app

COPY --from=build \
{{- range $name, $config := $binaries }}
    /app/{{ $name }} \
{{- end }}
    ./

{{- $entrypoint := "launcher.sh" }}

{{- if eq .Binaries 1 }}

{{- /* directly use the only binary */ -}}
{{- range $name, $config := $binaries }}
{{- $entrypoint = $name }}
{{- end }}

{{- end }}

{{- /* copy launcher if the entrypoint is the launcher */ -}}
{{- if eq $entrypoint "launcher.sh" }}
COPY launcher.sh launcher.sh
{{- end }}

EXPOSE {{ .Docker.Port | default 3000 }}

ENTRYPOINT [ "/app/{{ $entrypoint }}" ]
{{- end }}
