{{- define "golang" }}

{{- $specifics := get .Languages "go" }}

{{- $binaries := dict }}
{{- $_ := map $binaries .Clis .Crons .Jobs .Workers }}

{{- $maintainer := index .Repository.Maintainers 0 }}

#############################
#        STAGE BUILD        #
#############################
FROM golang:{{ $specifics.Toolchain | default $specifics.Go }} AS build

ARG CGO_ENABLED=0
ARG GIT_REF_NAME
ARG GIT_COMMIT
ARG APP_VERSION=v0.0.0

WORKDIR /app

COPY . .

RUN go mod download{{ range $name, $_ := $binaries }} && \
    CGO_ENABLED=$CGO_ENABLED go build \
        -ldflags "\
            -X '{{ $specifics.Module }}/internal/build.branch=$GIT_REF_NAME' \
            -X '{{ $specifics.Module }}/internal/build.commit=$GIT_COMMIT' \
            -X '{{ $specifics.Module }}/internal/build.date=$(TZ="UTC" date '+%Y-%m-%dT%TZ')' \
            -X '{{ $specifics.Module }}/internal/build.version=$APP_VERSION' \
        " \
        -o {{ $name }} ./cmd/{{ $name }}
{{- end }}

#############################
#         STAGE RUN         #
#############################
FROM gcr.io/distroless/static-debian12:nonroot

LABEL org.opencontainers.image.authors="{{ $maintainer.Name }}{{ if $maintainer.Email }} <{{ $maintainer.Email }}>{{ end }}"
LABEL org.opencontainers.image.vendor="{{ $maintainer.Name }}"

LABEL org.opencontainers.image.title="{{ .Repository.VCS.ProjectName }}{{ with .Slug }}/{{ . }}{{ end }}"
{{- if .Repository.Description }}
LABEL org.opencontainers.image.description="{{ .Repository.Description }}"
{{- end }}
{{- if .Repository.License }}
LABEL org.opencontainers.image.licenses="{{ upper .Repository.License }}"
{{- end }}
LABEL org.opencontainers.image.url="{{ print .Repository.VCS.ProjectHost "/" .Repository.VCS.ProjectPath }}"
LABEL org.opencontainers.image.source="{{ print .Repository.VCS.ProjectHost "/" .Repository.VCS.ProjectPath }}"
LABEL org.opencontainers.image.documentation="{{ print .Repository.VCS.ProjectHost "/" .Repository.VCS.ProjectPath }}"

WORKDIR /app

COPY --from=build \
{{- range $name, $_ := $binaries }}
    /app/{{ $name }} \
{{- end }}
    ./

{{- $entrypoint := "launcher.sh" }}

{{- if eq .Binaries 1 }}

{{- /* directly use the only binary */ -}}
{{- range $name, $_ := $binaries }}
{{- $entrypoint = $name }}
{{- end }}

{{- end }}

{{- /* copy launcher if the entrypoint is the launcher */ -}}
{{- if eq $entrypoint "launcher.sh" }}
COPY launcher.sh launcher.sh
{{- end }}

EXPOSE {{ .Repository.Docker.Port | default 3000 }}

ENTRYPOINT [ "/app/{{ $entrypoint }}" ]
{{- end }}
