{{- define "node" }}

{{- $specifics := get .Languages "node" }}
{{- $manager := cutAfter $specifics.PackageManager "@" }}

{{- $maintainer := index .Parent.Config.Maintainers 0 }}

#############################
#        STAGE BUILD        #
#############################
FROM node:lts-alpine3.23 AS build

ARG APP_VERSION=v0.0.0

WORKDIR /app

COPY . .

RUN {{ $manager }} {{ eq $manager "npm" | ternary "ci" "install --frozen-lockfile" }} && \
    {{ $manager }} run build

#############################
#         STAGE RUN         #
#############################
FROM nginx:1.31.5-alpine3.24@sha256:72ba65eb42c10344912a84ff42408db7d34f2feb642204570ab8fc5ffd29f1d3

LABEL org.opencontainers.image.authors="{{ $maintainer.Name }}{{ if $maintainer.Email }} <{{ $maintainer.Email }}>{{ end }}"
LABEL org.opencontainers.image.vendor="{{ $maintainer.Name }}"

LABEL org.opencontainers.image.title="{{ .Parent.VCS.ProjectName }}{{ with .Slug }}/{{ . }}{{ end }}"
{{- if .Parent.Config.Description }}
LABEL org.opencontainers.image.description="{{ .Parent.Config.Description }}"
{{- end }}
{{- if .Parent.Config.License }}
LABEL org.opencontainers.image.licenses="{{ upper .Parent.Config.License }}"
{{- end }}
LABEL org.opencontainers.image.url="{{ print .Parent.VCS.ProjectHost "/" .Parent.VCS.ProjectPath }}"
LABEL org.opencontainers.image.source="{{ print .Parent.VCS.ProjectHost "/" .Parent.VCS.ProjectPath }}"
LABEL org.opencontainers.image.documentation="{{ print .Parent.VCS.ProjectHost "/" .Parent.VCS.ProjectPath }}"

WORKDIR /app

COPY --from=build /app/dist /usr/share/nginx/html

RUN sed -i 's#listen 80;#listen {{ .Parent.Config.Docker.Port | default 3000 }};#' /etc/nginx/conf.d/default.conf

EXPOSE {{ .Parent.Config.Docker.Port | default 3000 }}
{{- end }}
