{{- define "node" }}

{{- $specifics := get .Languages "node" }}
{{- $manager := cutAfter $specifics.PackageManager "@" }}

{{- $maintainer := index .Parent.Config.Maintainers 0 }}

#############################
#        STAGE BUILD        #
#############################
FROM node:26.5.1-alpine3.24@sha256:233761595746769ebfdb6090f44fc7cdf818ae0ce62d2b37e0367723b9823e36 AS build

ARG APP_VERSION=v0.0.0

WORKDIR /app

COPY . .

RUN {{ $manager }} {{ eq $manager "npm" | ternary "ci" "install --frozen-lockfile" }} && \
    {{ $manager }} run build

#############################
#         STAGE RUN         #
#############################
FROM nginx:1.31.3-alpine3.24@sha256:4a73073bd557c65b759505da037898b61f1be6cbcc3c2c3aeac22d2a470c1752

LABEL org.opencontainers.image.authors="{{ $maintainer.Name }}{{ if $maintainer.Email }} <{{ $maintainer.Email }}>{{ end }}"
LABEL org.opencontainers.image.vendor="{{ $maintainer.Name }}"

LABEL org.opencontainers.image.title="{{ .Parent.VCS.ProjectName }}{{ with .Slug }}/{{ . }}{{ end }}"
{{- if .Parent.Config.Description }}
LABEL org.opencontainers.image.description="{{ .Parent.Config.Description }}"
{{- end }}
{{- if .Parent.Config.License }}
LABEL org.opencontainers.image.licenses="{{ upper .Parent.Config.License }}"
{{- end }}
LABEL org.opencontainers.image.url="{{ print .Parent.VCS.ProjectHost "/" .Parent.VCS.ProjectPath }}"
LABEL org.opencontainers.image.source="{{ print .Parent.VCS.ProjectHost "/" .Parent.VCS.ProjectPath }}"
LABEL org.opencontainers.image.documentation="{{ print .Parent.VCS.ProjectHost "/" .Parent.VCS.ProjectPath }}"

WORKDIR /app

COPY --from=build /app/dist /usr/share/nginx/html

RUN sed -i 's#listen 80;#listen {{ .Parent.Config.Docker.Port | default 3000 }};#' /etc/nginx/conf.d/default.conf

EXPOSE {{ .Parent.Config.Docker.Port | default 3000 }}
{{- end }}
