{{- define "golang" }}

{{- $specifics := get .Languages "go" }}

{{- $binaries := dict }}
{{- $_ := map $binaries .Clis .Crons .Jobs .Workers }}

{{- $maintainer := index .Parent.Config.Maintainers 0 }}

#############################
#        STAGE BUILD        #
#############################
FROM golang:{{ $specifics.Toolchain | default $specifics.Go }} AS build

ARG CGO_ENABLED=0
ARG GIT_REF_NAME
ARG GIT_COMMIT
ARG APP_VERSION=v0.0.0

WORKDIR /app

COPY . .

RUN go mod download{{ range $name, $_ := $binaries }} && \
    CGO_ENABLED=$CGO_ENABLED go build \
        -ldflags "\
            -X '{{ $specifics.Module }}/internal/build.branch=$GIT_REF_NAME' \
            -X '{{ $specifics.Module }}/internal/build.commit=$GIT_COMMIT' \
            -X '{{ $specifics.Module }}/internal/build.date=$(TZ="UTC" date '+%Y-%m-%dT%TZ')' \
            -X '{{ $specifics.Module }}/internal/build.version=$APP_VERSION' \
        " \
        -o {{ $name }} ./cmd/{{ $name }}
{{- end }}

#############################
#         STAGE RUN         #
#############################
FROM gcr.io/distroless/static-debian13:nonroot@sha256:f7f8f729987ad0fdf6b05eeeae94b26e6a0f613bdf46feea7fc40f7bd72953e6

LABEL org.opencontainers.image.authors="{{ $maintainer.Name }}{{ if $maintainer.Email }} <{{ $maintainer.Email }}>{{ end }}"
LABEL org.opencontainers.image.vendor="{{ $maintainer.Name }}"

LABEL org.opencontainers.image.title="{{ .Parent.VCS.ProjectName }}{{ with .Slug }}/{{ . }}{{ end }}"
{{- if .Parent.Config.Description }}
LABEL org.opencontainers.image.description="{{ .Parent.Config.Description }}"
{{- end }}
{{- if .Parent.Config.License }}
LABEL org.opencontainers.image.licenses="{{ upper .Parent.Config.License }}"
{{- end }}
LABEL org.opencontainers.image.url="{{ print .Parent.VCS.ProjectHost "/" .Parent.VCS.ProjectPath }}"
LABEL org.opencontainers.image.source="{{ print .Parent.VCS.ProjectHost "/" .Parent.VCS.ProjectPath }}"
LABEL org.opencontainers.image.documentation="{{ print .Parent.VCS.ProjectHost "/" .Parent.VCS.ProjectPath }}"

WORKDIR /app

COPY --from=build \
{{- range $name, $_ := $binaries }}
    /app/{{ $name }} \
{{- end }}
    ./

{{- $entrypoint := "launcher.sh" }}

{{- if eq .Binaries 1 }}

{{- /* directly use the only binary */ -}}
{{- range $name, $_ := $binaries }}
{{- $entrypoint = $name }}
{{- end }}

{{- end }}

{{- /* copy launcher if the entrypoint is the launcher */ -}}
{{- if eq $entrypoint "launcher.sh" }}
COPY launcher.sh launcher.sh
{{- end }}

EXPOSE {{ .Parent.Config.Docker.Port | default 3000 }}

ENTRYPOINT [ "/app/{{ $entrypoint }}" ]
{{- end }}
