#!/bin/sh
# Code generated by kickr; DO NOT EDIT.

base_branch=
if [ -n "$GITHUB_BASE_REF" ]; then
  base_branch=origin/$GITHUB_BASE_REF
elif [ -n "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" ]; then
  base_branch="origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
else
  base_branch=HEAD~1
fi

type="(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)"
scope="(\(.+\))?"
conventionalcommit="^${type}${scope}(!)?:[[:space:]].+$"

echo "validating commits against $base_branch"

commits=$(git log --pretty=format:%s "${base_branch}..HEAD")
errors=0
while IFS= read -r commit; do
  echo "validating '$commit' with conventional commits specification"
  if ! echo "$commit" | grep -qE "$conventionalcommit"; then
    errors=$((errors+1))
  fi
done <<EOF
$commits
EOF

if [ "$errors" -ne 0 ]; then
  echo "invalid commits present between $base_branch and HEAD"
  exit 1
else
  echo "all commits are valid"
fi
