package generate_test

import (
	"bytes"
	"net/http"
	"os"
	"path/filepath"
	"testing"

	"github.com/jarcoal/httpmock"
	"github.com/kickr-dev/engine/pkg/generator"
	"github.com/kickr-dev/engine/pkg/parser"
	compare "github.com/kilianpaquier/compare/pkg"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/kickr-dev/kickr/pkg/generate"
	"github.com/kickr-dev/kickr/pkg/generate/types"
	kickr "github.com/kickr-dev/kickr/pkg/kickr/v1"
)

func TestGeneratorGitignore(t *testing.T) {
	ctx := t.Context()

	httpmock.Activate()
	t.Cleanup(httpmock.DeactivateAndReset)
	gen := generate.GeneratorGitignore(http.DefaultClient)

	t.Run("error_http_call", func(t *testing.T) {
		// Arrange
		httpmock.RegisterResponder(http.MethodGet, "https://www.toptal.com/developers/gitignore/api/dotenv",
			httpmock.NewStringResponder(http.StatusInternalServerError, "some error"))

		// Act
		err := gen(ctx, t.TempDir(), types.KickrGen{})

		// Assert
		assert.ErrorContains(t, err, "download gitignore")
	})

	t.Run("success", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()

		httpmock.RegisterResponder(http.MethodGet, "https://www.toptal.com/developers/gitignore/api/go,dotenv,sonar,sonarqube",
			httpmock.NewStringResponder(http.StatusOK, "some content"))

		config := types.KickrGen{
			Kickr:     kickr.Kickr{CI: &kickr.CI{Options: []string{kickr.OptionSonarQube}}},
			Languages: map[string]any{"go": nil},
		}

		// Act
		err := gen(ctx, destdir, config)

		// Assert
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(destdir, generator.FileGitignore))
		require.NoError(t, err)
		assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
reports/

some content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))
	})

	t.Run("success_with_binaries", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()

		httpmock.RegisterResponder(http.MethodGet, "https://www.toptal.com/developers/gitignore/api/go,dotenv,sonar,sonarqube",
			httpmock.NewStringResponder(http.StatusOK, "some content"))

		config := types.KickrGen{
			Kickr: kickr.Kickr{CI: &kickr.CI{Options: []string{kickr.OptionSonarQube}}},
			Executables: parser.Executables{
				Clis:    map[string]struct{}{"cli": {}},
				Crons:   map[string]struct{}{"cron": {}},
				Jobs:    map[string]struct{}{"job": {}},
				Workers: map[string]struct{}{"worker": {}},
			},
			Languages: map[string]any{"go": nil},
		}

		// Act
		err := gen(ctx, destdir, config)

		// Assert
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(destdir, generator.FileGitignore))
		require.NoError(t, err)
		assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
reports/

# Binaries for programs
cli
!cli/
cron-*
!cron-*/
job-*
!job-*/
worker-*
!worker-*/

some content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))
	})
}
