// Code generated by AI (Claude Opus 5.5)

package generate_test

import (
	"os"
	"path/filepath"
	"testing"

	engine "github.com/kickr-dev/engine/pkg"
	"github.com/kickr-dev/engine/pkg/files"
	"github.com/kickr-dev/engine/pkg/parser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/kickr-dev/kickr/pkg/generate"
	"github.com/kickr-dev/kickr/pkg/generate/types"
	kickr "github.com/kickr-dev/kickr/pkg/kickr/v1"
)

func TestGeneratorCONTRIBUTING(t *testing.T) {
	ctx := t.Context()

	repo := types.Repository{
		Config: kickr.Kickr{GitLab: &kickr.GitLab{}, Platform: kickr.PlatformGitLab},
		VCS: parser.VCS{
			Platform:    kickr.PlatformGitLab,
			ProjectHost: kickr.PlatformGitLab + ".com",
			ProjectName: "kickr",
			ProjectPath: "kickr-dev/kickr",
		},
	}

	guidelines := "<!-- BEGIN_KICKR_GUIDELINES -->\n" + `Thanks for taking the time to contribute!

By participating in this project you agree to abide by the [Code of Conduct](CODE_OF_CONDUCT.md).

## How to contribute

1. Search [existing work items](https://gitlab.com/kickr-dev/kickr/-/work_items) before opening a new one.
2. Fork the repository and create a branch off the default branch.
3. Make your change, add or update tests (extend existing tests whenever possible), update docs.
4. Open a [merge request](https://gitlab.com/kickr-dev/kickr/-/merge_requests).

Files with ` + "`Code generated by kickr; DO NOT EDIT.`" + ` header are regenerated on each layout update, manual edits get overwritten.
Remove the header to opt a file out of regeneration, unless ` + "`kickr generate -f`" + ` is used.

## Commit messages

Commits must follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/): ` + "`type(scope): summary`" + ` (scope optional).
A ` + "`!`" + ` after type/scope, or a ` + "`BREAKING CHANGE:`" + ` footer, forces a major release regardless of type.

| Type       | Purpose                                 | Release |
| ---------- | --------------------------------------- | ------- |
| ` + "`feat`" + `     | New feature                             | minor   |
| ` + "`fix`" + `      | Bug fix                                 | patch   |
| ` + "`perf`" + `     | Performance improvement                 | patch   |
| ` + "`refactor`" + ` | Code change, no behavior change         | minor   |
| ` + "`revert`" + `   | Reverts a previous commit               | patch   |
| ` + "`docs`" + `     | Documentation only                      | patch   |
| ` + "`chore`" + `    | Tooling, deps, config, preparatory work | patch   |
| ` + "`build`" + `    | Build system or dependencies            | none    |
| ` + "`ci`" + `       | CI configuration                        | none    |
| ` + "`style`" + `    | Formatting, no code meaning change      | none    |
| ` + "`test`" + `     | Adding or fixing tests                  | none    |

## Pre-commit hooks

This repo uses [pre-commit](https://pre-commit.com).
Install it and run ` + "`pre-commit install`" + ` once, hooks then run automatically on commit.

## Code review

Every change goes through review before merge.
Keep commits separate and functional (one logical change per commit, no dumping-ground commits).
Force-pushing to update a review branch is fine.
<!-- END_KICKR_GUIDELINES -->`

	generated := "# Contributing\n\n" + guidelines + "\n"

	t.Run("success_missing_contributing", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()

		// Act
		err := generate.GeneratorCONTRIBUTING(ctx, destdir, repo)

		// Assert
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(destdir, "CONTRIBUTING.md"))
		require.NoError(t, err)
		assert.Equal(t, generated, string(content))
	})

	t.Run("success_forced_regenerates_contributing", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()
		dest := filepath.Join(destdir, "CONTRIBUTING.md")
		require.NoError(t, os.WriteFile(dest, []byte("# Custom title\n\nCustom content.\n"), files.RwRR))

		// Act
		err := generate.GeneratorCONTRIBUTING(ctx, destdir, repo)

		// Assert
		require.NoError(t, err)
		content, err := os.ReadFile(dest)
		require.NoError(t, err)
		assert.Equal(t, generated, string(content))
	})

	t.Run("not_forced", func(t *testing.T) {
		// tests under this package are run with --force by default to ensure all testdata are regenerated when needed
		// tests below must be run without the option to ensure a current content is kept
		logger := engine.GetLogger()
		engine.Configure(engine.WithForce(false), engine.WithLogger(logger))
		t.Cleanup(func() { engine.Configure(engine.WithForce(true), engine.WithLogger(logger)) })

		t.Run("success_refresh_guidelines", func(t *testing.T) {
			// Arrange
			destdir := t.TempDir()
			dest := filepath.Join(destdir, "CONTRIBUTING.md")
			require.NoError(t, os.WriteFile(dest, []byte(`# Custom title

<!-- BEGIN_KICKR_GUIDELINES -->
Stale guidelines.
<!-- END_KICKR_GUIDELINES -->

Custom content.
`), files.RwRR))

			// Act
			err := generate.GeneratorCONTRIBUTING(ctx, destdir, repo)

			// Assert
			require.NoError(t, err)
			content, err := os.ReadFile(dest)
			require.NoError(t, err)
			assert.Equal(t, "# Custom title\n\n"+guidelines+"\n\nCustom content.\n", string(content))
		})

		t.Run("success_no_markers", func(t *testing.T) {
			// Arrange
			destdir := t.TempDir()
			dest := filepath.Join(destdir, "CONTRIBUTING.md")
			contributing := "# Custom title\n\nCustom content.\n"
			require.NoError(t, os.WriteFile(dest, []byte(contributing), files.RwRR))

			// Act
			err := generate.GeneratorCONTRIBUTING(ctx, destdir, repo)

			// Assert
			require.NoError(t, err)
			content, err := os.ReadFile(dest)
			require.NoError(t, err)
			assert.Equal(t, contributing, string(content))
		})
	})
}

func TestGeneratorCONTRIBUTING_Exclude(t *testing.T) {
	ctx := t.Context()

	repo := types.Repository{Config: kickr.Kickr{Exclude: []string{kickr.ExcludeContributing}}}

	t.Run("error_remove_contributing", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()
		dest := filepath.Join(destdir, "CONTRIBUTING.md")
		require.NoError(t, os.MkdirAll(filepath.Join(dest, "file.txt"), files.RwxRxRxRx))

		// Act
		err := generate.GeneratorCONTRIBUTING(ctx, destdir, repo)

		// Assert
		assert.ErrorContains(t, err, "remove 'CONTRIBUTING.md'")
	})

	t.Run("success_remove_existing_contributing", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()
		dest := filepath.Join(destdir, "CONTRIBUTING.md")
		require.NoError(t, os.WriteFile(dest, []byte("# Contributing\n"), files.RwRR))

		// Act
		err := generate.GeneratorCONTRIBUTING(ctx, destdir, repo)

		// Assert
		require.NoError(t, err)
		assert.NoFileExists(t, dest)
	})

	t.Run("success_missing_contributing", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()

		// Act
		err := generate.GeneratorCONTRIBUTING(ctx, destdir, repo)

		// Assert
		require.NoError(t, err)
		assert.NoFileExists(t, filepath.Join(destdir, "CONTRIBUTING.md"))
	})
}
