// Code generated by AI (Claude Opus 5.5)

package generate

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	engine "github.com/kickr-dev/engine/pkg"

	"github.com/kickr-dev/kickr/pkg/generate/templates"
	"github.com/kickr-dev/kickr/pkg/generate/types"
)

// GeneratorREADME writes the repository README.md file with the badges matching kickr configuration (releases, CI, coverage, etc.).
//
// An existing README.md is kept as is, except for the badges between
// "<!-- BEGIN_KICKR_BADGES -->" and "<!-- END_KICKR_BADGES -->" markers, which are regenerated.
//
// Forced generation rewrites the whole README.md.
func GeneratorREADME(_ context.Context, destdir string, repo types.Repository) error {
	type data struct {
		types.Repository //nolint:embeddedstructfieldcheck
		Content          string
	}

	template := engine.Template[data]{
		Delimiters:     engine.DelimitersBracket(),
		GeneratePolicy: engine.PolicyAlways,
		Globs:          engine.GlobsWithPart("README.md"),
		Out:            "README.md",
	}

	var content []byte
	if !engine.Forced() {
		existing, err := os.ReadFile(filepath.Join(destdir, template.Out))
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("read '%s': %w", template.Out, err)
		}
		content = existing
	}

	d := data{Content: string(content), Repository: repo}
	if err := engine.ApplyTemplate(templates.FS(), destdir, template, d); err != nil {
		return fmt.Errorf("apply template: %w", err)
	}
	return nil
}

var _ engine.Generator[types.Repository] = GeneratorREADME // ensure interface is implemented
