// Code generated by AI (Claude Opus 5.5)

package generate

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"

	engine "github.com/kickr-dev/engine/pkg"

	"github.com/kickr-dev/kickr/pkg/generate/templates"
	"github.com/kickr-dev/kickr/pkg/generate/types"
	kickr "github.com/kickr-dev/kickr/pkg/kickr/v1"
)

// GeneratorCONTRIBUTING writes the repository CONTRIBUTING.md file with the guidelines matching kickr configuration (platform, pre-commit, etc.).
//
// An existing CONTRIBUTING.md is kept as is, except for the guidelines between
// "<!-- BEGIN_KICKR_GUIDELINES -->" and "<!-- END_KICKR_GUIDELINES -->" markers, which are regenerated.
//
// Forced generation rewrites the whole CONTRIBUTING.md.
//
// When 'contributing' is excluded, an existing CONTRIBUTING.md is removed.
func GeneratorCONTRIBUTING(_ context.Context, destdir string, repo types.Repository) error {
	type data struct {
		types.Repository //nolint:embeddedstructfieldcheck
		Content          string
	}

	template := engine.Template[data]{
		Delimiters:     engine.DelimitersBracket(),
		GeneratePolicy: engine.PolicyAlways,
		Globs:          engine.GlobsWithPart("CONTRIBUTING.md"),
		Out:            "CONTRIBUTING.md",
	}

	if slices.Contains(repo.Config.Exclude, kickr.ExcludeContributing) {
		engine.GetLogger().Infof("skipping contributing generation, '%s' is excluded", kickr.ExcludeContributing)
		if err := os.Remove(filepath.Join(destdir, template.Out)); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("remove '%s': %w", template.Out, err)
		}
		return nil
	}

	var content []byte
	if !engine.Forced() {
		existing, err := os.ReadFile(filepath.Join(destdir, template.Out))
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("read '%s': %w", template.Out, err)
		}
		content = existing
	}

	d := data{Content: string(content), Repository: repo}
	if err := engine.ApplyTemplate(templates.FS(), destdir, template, d); err != nil {
		return fmt.Errorf("apply template: %w", err)
	}
	return nil
}

var _ engine.Generator[types.Repository] = GeneratorCONTRIBUTING // ensure interface is implemented
