package generate_test

import (
	"bytes"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/jarcoal/httpmock"
	"github.com/kickr-dev/engine/pkg/generator"
	"github.com/kickr-dev/engine/pkg/parser"
	compare "github.com/kilianpaquier/compare/pkg"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/kickr-dev/kickr/pkg/generate"
	"github.com/kickr-dev/kickr/pkg/generate/types"
	kickr "github.com/kickr-dev/kickr/pkg/kickr/v1"
)

func TestGeneratorGitignore(t *testing.T) {
	ctx := t.Context()

	httpmock.Activate()
	t.Cleanup(httpmock.DeactivateAndReset)
	gen := generate.GeneratorGitignore(http.DefaultClient)

	mockURL := func(t *testing.T, templates ...string) string {
		t.Helper()
		u, err := url.JoinPath(generator.GitignoreBaseURL, strings.Join(templates, ","))
		require.NoError(t, err)
		return u
	}

	t.Run("error_http_call", func(t *testing.T) {
		// Arrange
		t.Cleanup(httpmock.Reset)
		httpmock.RegisterResponder(http.MethodGet, mockURL(t, "dotenv"),
			httpmock.NewStringResponder(http.StatusInternalServerError, "some error"))

		repo := types.Repository{
			Modules: []types.Module{
				{Directory: types.RootModule},
			},
		}

		// Act
		err := gen(ctx, t.TempDir(), repo)

		// Assert
		assert.ErrorContains(t, err, "download gitignore")
	})

	t.Run("success_languages", func(t *testing.T) {
		// Arrange
		langs := map[string][]string{
			types.LanguageGo:        {"go"},
			types.LanguageHelm:      {"helm"},
			types.LanguageTerraform: {"terraform"},
		}

		for lang, keys := range langs {
			t.Run(lang, func(t *testing.T) {
				// Arrange
				destdir := t.TempDir()
				query := slices.Concat([]string{"dotenv"}, keys)

				t.Cleanup(httpmock.Reset)
				httpmock.RegisterResponder(http.MethodGet, mockURL(t, query...),
					httpmock.NewStringResponder(http.StatusOK, "some content"))

				repo := types.Repository{
					Modules: []types.Module{
						{
							Directory: types.RootModule,
							Languages: map[string]any{lang: struct{}{}},
						},
					},
				}

				// Act
				err := gen(ctx, destdir, repo)

				// Assert
				require.NoError(t, err)
				content, err := os.ReadFile(filepath.Join(destdir, generator.FileGitignore))
				require.NoError(t, err)
				assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
logs/
reports/
tmp/

some content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))
			})
		}
	})

	t.Run("success_hugo", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()

		t.Cleanup(httpmock.Reset)
		httpmock.RegisterResponder(http.MethodGet, mockURL(t, "dotenv", "hugo"),
			httpmock.NewStringResponder(http.StatusOK, "some content"))

		repo := types.Repository{
			Modules: []types.Module{
				{
					Directory: types.RootModule,
					Languages: map[string]any{types.LanguageHugo: struct{}{}},
				},
			},
		}

		// Act
		err := gen(ctx, destdir, repo)

		// Assert
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(destdir, generator.FileGitignore))
		require.NoError(t, err)
		assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
logs/
reports/
tmp/

# Hugo direct module checksums
hugo.direct.sum

some content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))
	})

	t.Run("success_netlify", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()

		t.Cleanup(httpmock.Reset)
		httpmock.RegisterResponder(http.MethodGet, mockURL(t, "dotenv"),
			httpmock.NewStringResponder(http.StatusOK, "some content"))

		repo := types.Repository{
			Modules: []types.Module{
				{
					Directory: types.RootModule,
					Config:    kickr.Module{Path: types.RootModule, Deployment: &kickr.Deployment{Target: kickr.DeploymentTargetNetlify}},
				},
			},
		}

		// Act
		err := gen(ctx, destdir, repo)

		// Assert
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(destdir, generator.FileGitignore))
		require.NoError(t, err)
		assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
logs/
reports/
tmp/

# Local Netlify folder
.netlify

some content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))
	})

	t.Run("success_bun", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()

		t.Cleanup(httpmock.Reset)
		httpmock.RegisterResponder(http.MethodGet, mockURL(t, "dotenv", "node"),
			httpmock.NewStringResponder(http.StatusOK, "some content"))

		repo := types.Repository{
			Modules: []types.Module{
				{
					Directory: types.RootModule,
					Languages: map[string]any{types.LanguageNode: parser.PackageJSON{PackageManager: "bun@1.1.6"}},
				},
			},
		}

		// Act
		err := gen(ctx, destdir, repo)

		// Assert
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(destdir, generator.FileGitignore))
		require.NoError(t, err)
		assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
logs/
reports/
tmp/

# Bun cache directory
.bun

some content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))
	})

	t.Run("success_modules", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()

		t.Cleanup(httpmock.Reset)
		httpmock.RegisterResponder(http.MethodGet, mockURL(t, "dotenv", "go"),
			httpmock.NewStringResponder(http.StatusOK, "go content"))
		httpmock.RegisterResponder(http.MethodGet, mockURL(t, "dotenv", "hugo"),
			httpmock.NewStringResponder(http.StatusOK, "hugo content"))

		repo := types.Repository{
			Modules: []types.Module{
				{Directory: types.RootModule, Languages: map[string]any{types.LanguageGo: nil}},
				{Directory: "docs", Languages: map[string]any{types.LanguageHugo: nil}},
			},
		}

		// Act
		err := gen(ctx, destdir, repo)

		// Assert
		require.NoError(t, err)

		// each module only gets the exclusions of the languages it's made of
		content, err := os.ReadFile(filepath.Join(destdir, generator.FileGitignore))
		require.NoError(t, err)
		assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
logs/
reports/
tmp/

go content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))

		content, err = os.ReadFile(filepath.Join(destdir, "docs", generator.FileGitignore))
		require.NoError(t, err)
		assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
logs/
reports/
tmp/

# Hugo direct module checksums
hugo.direct.sum

hugo content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))
	})

	t.Run("success_with_binaries", func(t *testing.T) {
		testcases := []kickr.Kickr{
			{GitHub: &kickr.GitHub{Options: []string{kickr.GitHubOptionsSonarQube}}, Platform: parser.GitHub},
			{GitLab: &kickr.GitLab{Options: []string{kickr.GitLabOptionsSonarQube}}, Platform: parser.GitLab},
		}
		for _, tc := range testcases {
			t.Run(tc.Platform, func(t *testing.T) {
				// Arrange
				destdir := t.TempDir()

				t.Cleanup(httpmock.Reset)
				httpmock.RegisterResponder(http.MethodGet, mockURL(t, "dotenv", "go", "sonar", "sonarqube"),
					httpmock.NewStringResponder(http.StatusOK, "some content"))

				repo := types.Repository{
					Config: tc,
					Modules: []types.Module{
						{
							Directory: types.RootModule,
							Executables: parser.Executables{
								Clis:    map[string]any{"cli": struct{}{}},
								Crons:   map[string]any{"cron": struct{}{}},
								Jobs:    map[string]any{"job": struct{}{}},
								Workers: map[string]any{"worker": struct{}{}},
							},
							Languages: map[string]any{types.LanguageGo: nil},
						},
					},
				}

				// Act
				err := gen(ctx, destdir, repo)

				// Assert
				require.NoError(t, err)
				content, err := os.ReadFile(filepath.Join(destdir, generator.FileGitignore))
				require.NoError(t, err)
				assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
logs/
reports/
tmp/

# Binaries for programs
cli
!cli/
cron-*
!cron-*/
job-*
!job-*/
worker-*
!worker-*/

some content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))
			})
		}
	})
}
