// Code generated by AI (Claude Opus 5.5)

package generate_test

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	engine "github.com/kickr-dev/engine/pkg"
	"github.com/kickr-dev/engine/pkg/files"
	"github.com/kickr-dev/engine/pkg/parser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/kickr-dev/kickr/pkg/generate"
	"github.com/kickr-dev/kickr/pkg/generate/types"
	kickr "github.com/kickr-dev/kickr/pkg/kickr/v1"
)

func TestGeneratorREADME(t *testing.T) {
	ctx := t.Context()

	repo := types.Repository{
		Config: kickr.Kickr{GitLab: &kickr.GitLab{}, Platform: kickr.PlatformGitLab},
		VCS: parser.VCS{
			Platform:    kickr.PlatformGitLab,
			ProjectHost: kickr.PlatformGitLab + ".com",
			ProjectName: "kickr",
			ProjectPath: "kickr-dev/kickr",
		},
	}

	generated := `<!-- BEGIN_KICKR_BADGES -->
[![GitLab Issues](https://img.shields.io/gitlab/issues/open/kickr-dev%2Fkickr?gitlab_url=https%3A%2F%2Fgitlab.com&style=for-the-badge)](https://gitlab.com/kickr-dev/kickr/-/work_items)
[![GitLab CICD](https://img.shields.io/gitlab/pipeline-status/kickr-dev%2Fkickr?gitlab_url=https%3A%2F%2Fgitlab.com&branch=main&style=for-the-badge)](https://gitlab.com/kickr-dev/kickr/-/pipelines?ref=main)
[![Plumber Score](https://img.shields.io/endpoint?url=https%3A%2F%2Fscore.getplumber.io%2Fgitlab.com%2Fkickr-dev%2Fkickr.json&style=for-the-badge)](https://score.getplumber.io/gitlab.com/kickr-dev/kickr)
<!-- END_KICKR_BADGES -->`

	t.Run("success_missing_readme", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()

		// Act
		err := generate.GeneratorREADME(ctx, destdir, repo)

		// Assert
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(destdir, "README.md"))
		require.NoError(t, err)
		assert.Equal(t, fmt.Sprintf("# kickr <!-- omit in toc -->\n\n<div align=\"center\">\n\n%s\n\n</div>\n\n---\n", generated), string(content))
	})

	t.Run("success_forced_regenerates_readme", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()
		dest := filepath.Join(destdir, "README.md")
		require.NoError(t, os.WriteFile(dest, []byte("# Custom title\n\nCustom content.\n"), files.RwRR))

		// Act
		err := generate.GeneratorREADME(ctx, destdir, repo)

		// Assert
		require.NoError(t, err)
		content, err := os.ReadFile(dest)
		require.NoError(t, err)
		assert.Equal(t, fmt.Sprintf("# kickr <!-- omit in toc -->\n\n<div align=\"center\">\n\n%s\n\n</div>\n\n---\n", generated), string(content))
	})

	t.Run("not_forced", func(t *testing.T) {
		// tests under this package are run with --force by default to ensure all testdata are regenerated when needed
		// tests below must be run without the option to ensure a current content is kept
		logger := engine.GetLogger()
		engine.Configure(engine.WithForce(false), engine.WithLogger(logger))
		t.Cleanup(func() { engine.Configure(engine.WithForce(true), engine.WithLogger(logger)) })

		t.Run("success_refresh_badges", func(t *testing.T) {
			// Arrange
			destdir := t.TempDir()
			dest := filepath.Join(destdir, "README.md")
			require.NoError(t, os.WriteFile(dest, []byte(`# Custom title

<div align="center">

<!-- BEGIN_KICKR_BADGES -->
[![Stale](https://img.shields.io/stale)](https://example.com/stale)
<!-- END_KICKR_BADGES -->
[![Custom](https://img.shields.io/custom)](https://example.com/custom)

</div>

Custom content.
`), files.RwRR))

			// Act
			err := generate.GeneratorREADME(ctx, destdir, repo)

			// Assert
			require.NoError(t, err)
			content, err := os.ReadFile(dest)
			require.NoError(t, err)
			assert.Equal(t, fmt.Sprintf("# Custom title\n\n<div align=\"center\">\n\n%s\n[![Custom](https://img.shields.io/custom)](https://example.com/custom)\n\n</div>\n\nCustom content.\n", generated), string(content))
		})

		t.Run("success_no_markers", func(t *testing.T) {
			// Arrange
			destdir := t.TempDir()
			dest := filepath.Join(destdir, "README.md")
			readme := "# Custom title\n\nCustom content.\n"
			require.NoError(t, os.WriteFile(dest, []byte(readme), files.RwRR))

			// Act
			err := generate.GeneratorREADME(ctx, destdir, repo)

			// Assert
			require.NoError(t, err)
			content, err := os.ReadFile(dest)
			require.NoError(t, err)
			assert.Equal(t, readme, string(content))
		})
	})
}
