package generate_test

import (
	"bytes"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jarcoal/httpmock"
	"github.com/kickr-dev/engine/pkg/generator"
	"github.com/kickr-dev/engine/pkg/parser"
	compare "github.com/kilianpaquier/compare/pkg"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/kickr-dev/kickr/pkg/generate"
	"github.com/kickr-dev/kickr/pkg/generate/types"
	kickr "github.com/kickr-dev/kickr/pkg/kickr/v1"
)

func TestGeneratorGitignore(t *testing.T) {
	ctx := t.Context()

	httpmock.Activate()
	t.Cleanup(httpmock.DeactivateAndReset)
	gen := generate.GeneratorGitignore(http.DefaultClient)

	t.Run("error_http_call", func(t *testing.T) {
		// Arrange
		t.Cleanup(httpmock.Reset)
		httpmock.RegisterResponder(http.MethodGet, "https://www.toptal.com/developers/gitignore/api/dotenv",
			httpmock.NewStringResponder(http.StatusInternalServerError, "some error"))

		// Act
		err := gen(ctx, t.TempDir(), types.Repository{})

		// Assert
		assert.ErrorContains(t, err, "download gitignore")
	})

	t.Run("success_languages", func(t *testing.T) {
		// Arrange
		langs := map[string][]string{
			"go":        {"go"},
			"helm":      {"helm"},
			"hugo":      {"hugo"},
			"node":      {"node"},
			"shell":     nil,
			"terraform": {"terraform"},
		}

		for lang, keys := range langs {
			t.Run(lang, func(t *testing.T) {
				// Arrange
				destdir := t.TempDir()

				t.Cleanup(httpmock.Reset)
				httpmock.RegisterResponder(http.MethodGet, "https://www.toptal.com/developers/gitignore/api/"+strings.Join(append(keys, "dotenv"), ","),
					httpmock.NewStringResponder(http.StatusOK, "some content"))

				// Act
				err := gen(ctx, destdir, types.Repository{Languages: map[string]any{lang: struct{}{}}})

				// Assert
				require.NoError(t, err)
				content, err := os.ReadFile(filepath.Join(destdir, generator.FileGitignore))
				require.NoError(t, err)
				assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
reports/

some content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))
			})
		}
	})

	t.Run("success_with_binaries", func(t *testing.T) {
		// Arrange
		destdir := t.TempDir()

		t.Cleanup(httpmock.Reset)
		httpmock.RegisterResponder(http.MethodGet, "https://www.toptal.com/developers/gitignore/api/go,dotenv,sonar,sonarqube",
			httpmock.NewStringResponder(http.StatusOK, "some content"))

		config := types.Repository{
			Kickr: kickr.Kickr{CI: &kickr.CI{Options: []string{kickr.OptionsSonarQube}}},
			Executables: parser.Executables{
				Clis:    map[string]any{"cli": struct{}{}},
				Crons:   map[string]any{"cron": struct{}{}},
				Jobs:    map[string]any{"job": struct{}{}},
				Workers: map[string]any{"worker": struct{}{}},
			},
			Languages: map[string]any{"go": nil},
		}

		// Act
		err := gen(ctx, destdir, config)

		// Assert
		require.NoError(t, err)
		content, err := os.ReadFile(filepath.Join(destdir, generator.FileGitignore))
		require.NoError(t, err)
		assert.Equal(t, `# Code generated by kickr; DO NOT EDIT.

# Various build / compile directories
dist/
reports/

# Binaries for programs
cli
!cli/
cron-*
!cron-*/
job-*
!job-*/
worker-*
!worker-*/

some content`, string(bytes.ReplaceAll(content, compare.Carriage, []byte{})))
	})
}
