# Code generated by kickr; DO NOT EDIT.

.PHONY: clean
clean:
	@git clean -dfX

.PHONY: build-docs
build-docs:
	@hugo --gc --minify --destination dist --logLevel debug --source docs

.PHONY: serve-docs
serve-docs:
	@hugo server --disableFastRender --destination dist --logLevel debug --source docs

.PHONY: production-docs
production-docs:
	@netlify dev -c "make serve-docs" \
		--target-port 1313 --port 8888
		--dir dist
		--framework hugo
		--context production
