# Code generated by kickr; DO NOT EDIT.

APP_VERSION ?= v0.0.0

.PHONY: test
test:
	@go test ./... -count 1 -timeout=30s

.PHONY: test-race
test-race:
	@CGO_ENABLED=1 go test ./... -race -timeout=30s

.PHONY: test-cover
test-cover:
	@go test ./... -v -coverpkg="./..." -covermode="count" -timeout=30s
