# Code generated by kickr; DO NOT EDIT.

APP_VERSION ?= v0.0.0

.PHONY: test
test: ## run unit tests.
	@go test ./... -count 1 -timeout=30s

.PHONY: test-race
test-race: ## run unit tests with the race detector.
	@CGO_ENABLED=1 go test ./... -race -timeout=30s

.PHONY: test-cover
test-cover: ## run unit tests with coverage.
	@go test ./... -v -coverpkg="./..." -covermode="count" -timeout=30s

.PHONY: build
build: ## build the api binary.
	@CGO_ENABLED=0 go build \
		-ldflags "\
			-X 'github.com/kickr-dev/kickr/internal/build.branch=$(shell git rev-parse --abbrev-ref HEAD)' \
			-X 'github.com/kickr-dev/kickr/internal/build.commit=$(shell git rev-parse HEAD)' \
			-X 'github.com/kickr-dev/kickr/internal/build.date=$(shell TZ="UTC" date '+%Y-%m-%dT%TZ')' \
			-X 'github.com/kickr-dev/kickr/internal/build.version=${APP_VERSION}' \
		" \
		-o api ./cmd/api

.PHONY: docker
docker: ## build the docker image.
	@docker build . \
		-f Dockerfile \
		-t kickr/backend:${APP_VERSION} \
		--build-arg GIT_REF_NAME=$(shell git rev-parse --abbrev-ref HEAD) \
		--build-arg GIT_COMMIT=$(shell git rev-parse HEAD) \
		--build-arg APP_VERSION=${APP_VERSION}
