# Code generated by kickr; DO NOT EDIT.

APP_VERSION ?= v0.0.0

.PHONY: build
build:
	@hugo --gc --minify --destination dist --logLevel debug

.PHONY: serve
serve:
	@hugo server --disableFastRender --destination dist --logLevel debug

.PHONY: production
production:
	@netlify dev -c "make serve" \
		--target-port 1313 --port 8888
		--dir dist
		--framework hugo
		--context production
