package types

import (
	"github.com/kickr-dev/engine/pkg/parser"

	"github.com/kickr-dev/kickr/pkg/kickr/v1"
)

// Repository represents a repository being generated by kickr.
//
// A repository contains its kickr configuration and additional properties from languages parsing, files globing, etc.
type Repository struct {
	kickr.Kickr
	parser.Executables

	Globs     map[string]any
	Languages map[string]any
	VCS       parser.VCS
}

// SetLanguage sets a language with its specificities.
func (k *Repository) SetLanguage(name string, value any) {
	if k.Languages == nil {
		k.Languages = map[string]any{}
	}
	k.Languages[name] = value
}

// SetGlob sets a glob by its name.
func (k *Repository) SetGlob(name string, matches []string) {
	if k.Globs == nil {
		k.Globs = map[string]any{}
	}
	k.Globs[name] = matches
}

// Mono is a wrapper used for monorepository parsing.
// It helps identifying where is located a specific language.
type Mono[T any] struct {
	Directory string
	Specifics T
}
