package types //nolint:revive

import (
	"maps"
	"path/filepath"
	"slices"

	"github.com/kickr-dev/engine/pkg/parser"

	"github.com/kickr-dev/kickr/pkg/kickr/v1"
)

// RootModule is the directory of the repository's root module.
const RootModule = "."

// Repository represents a repository being generated by kickr.
//
// A repository contains its kickr configuration and additional properties from languages parsing, files globing, etc.
type Repository struct {
	Config  kickr.Kickr
	Modules []Module
	VCS     parser.VCS
}

// RepositoryModules returns all modules of the given repository.
func RepositoryModules(repo Repository) []Module {
	return repo.Modules
}

// HasLanguages returns truthy when at least one repository module contains a language.
func (r Repository) HasLanguages() bool {
	for _, module := range r.Modules {
		if len(module.Languages) > 0 {
			return true
		}
	}
	return false
}

// HasDocker returns truthy when at least one repository module gets a Dockerfile.
func (r Repository) HasDocker() bool {
	for _, module := range r.Modules {
		if module.HasDocker() {
			return true
		}
	}
	return false
}

// HasMakefile returns truthy when at least one repository module gets a Makefile.
func (r Repository) HasMakefile() bool {
	for _, module := range r.Modules {
		if module.HasMakefile() {
			return true
		}
	}
	return false
}

// FilterModules returns the repository modules matching the given predicate.
func (r Repository) FilterModules(predicate func(Module) bool) []Module {
	filtered := make([]Module, 0, len(r.Modules))
	for _, module := range r.Modules {
		if predicate(module) {
			filtered = append(filtered, module)
		}
	}
	return filtered
}

// ModulesWith returns the repository modules containing the provided language.
func (r Repository) ModulesWith(language string) []Module {
	return r.FilterModules(func(m Module) bool {
		_, ok := m.Languages[language]
		return ok
	})
}

// ModulesWithTerraformApply returns the repository modules with an apply strategy configured.
func (r Repository) ModulesWithTerraformApply() []Module {
	return r.FilterModules(func(m Module) bool { return m.Config.HasTerraformApply() })
}

// ModulesWithTerraformDocs returns the repository modules with terraform documentation needed.
func (r Repository) ModulesWithTerraformDocs() []Module {
	return r.FilterModules(func(m Module) bool { return m.Config.HasTerraformDocs() })
}

// ModuleIndexOf returns the index of the module matching the given directory,
// or -1 if not found.
func (r Repository) ModuleIndexOf(directory string) int {
	clean := filepath.Clean(directory)
	return slices.IndexFunc(r.Modules, func(m Module) bool {
		return m.Dir() == clean
	})
}

// ModulesWithDeployment returns the repository modules deployed on the input target.
//
// For static targets (netlify, pages), only hugo or node modules are returned
// since those are the only languages supporting static deployment.
func (r Repository) ModulesWithDeployment(target string) []Module {
	return r.FilterModules(func(m Module) bool {
		if !slices.Contains([]string{kickr.DeploymentTargetNetlify, kickr.DeploymentTargetPages}, target) {
			return m.Config.HasDeployment(target)
		}
		_, hugo := m.Languages[LanguageHugo]
		_, node := m.Languages[LanguageNode]
		return (hugo || node) && m.Config.HasDeployment(target)
	})
}

// HasGlob returns truthy when the root module matched the input glob name.
func (r Repository) HasGlob(name string) bool {
	if len(r.Modules) == 0 {
		return false
	}
	_, ok := r.Modules[0].Globs[name]
	return ok
}

// Executables returns the aggregation of every module's executables (clis, cronjobs, jobs, workers).
func (r Repository) Executables() parser.Executables {
	executables := parser.Executables{
		Clis:    map[string]any{},
		Crons:   map[string]any{},
		Jobs:    map[string]any{},
		Workers: map[string]any{},
	}
	for _, module := range r.Modules {
		maps.Copy(executables.Clis, module.Clis)
		maps.Copy(executables.Crons, module.Crons)
		maps.Copy(executables.Jobs, module.Jobs)
		maps.Copy(executables.Workers, module.Workers)
	}
	return executables
}
