package types //nolint:revive

import (
	"cmp"
	"maps"
	"path/filepath"
	"slices"

	"github.com/kickr-dev/engine/pkg/parser"

	"github.com/kickr-dev/kickr/pkg/kickr/v1"
)

// RootModule is the directory of the repository's root module.
const RootModule = "."

// Repository represents a repository being generated by kickr.
//
// A repository contains its kickr configuration and additional properties from languages parsing, files globing, etc.
type Repository struct {
	kickr.Kickr

	VCS     parser.VCS
	modules map[string]*Module
}

// HasLanguages returns truthy when at least one repository module contains a language.
func (r Repository) HasLanguages() bool {
	for _, module := range r.modules {
		if len(module.Languages) > 0 {
			return true
		}
	}
	return false
}

// HasDocker returns truthy when at least one repository module gets a Dockerfile.
func (r Repository) HasDocker() bool {
	for _, module := range r.modules {
		if module.HasDocker() {
			return true
		}
	}
	return false
}

// HasMakefile returns truthy when at least one repository module gets a Makefile.
func (r Repository) HasMakefile() bool {
	for _, module := range r.modules {
		if module.HasMakefile() {
			return true
		}
	}
	return false
}

// Modules returns the repository modules, sorted alphabetically.
func (r Repository) Modules() []Module {
	modules := make([]Module, 0, len(r.modules))
	for _, module := range r.modules {
		modules = append(modules, *module)
	}
	slices.SortFunc(modules, func(a, b Module) int {
		return cmp.Compare(a.directory, b.directory)
	})
	return modules
}

// ModulesWith returns the repository modules containing the provided language, sorted alphabetically.
func (r Repository) ModulesWith(language string) []Module {
	modules := make([]Module, 0, len(r.modules))
	for _, module := range r.Modules() {
		if _, ok := module.Languages[language]; ok {
			modules = append(modules, module)
		}
	}
	return modules
}

// HasLanguage returns truthy when at least one repository module contains the input language.
func (r Repository) HasLanguage(language string) bool {
	return len(r.ModulesWith(language)) > 0
}

// HasGlob returns truthy when the root module matched the input glob name.
func (r Repository) HasGlob(name string) bool {
	module, ok := r.modules[RootModule]
	if !ok {
		return false
	}
	_, ok = module.Globs[name]
	return ok
}

// Executables returns the aggregation of every module's executables (clis, cronjobs, jobs, workers).
func (r Repository) Executables() parser.Executables {
	executables := parser.Executables{
		Clis:    map[string]any{},
		Crons:   map[string]any{},
		Jobs:    map[string]any{},
		Workers: map[string]any{},
	}
	for _, module := range r.modules {
		maps.Copy(executables.Clis, module.Clis)
		maps.Copy(executables.Crons, module.Crons)
		maps.Copy(executables.Jobs, module.Jobs)
		maps.Copy(executables.Workers, module.Workers)
	}
	return executables
}

// Module creates or retrieves the module associated with the input directory.
//
// Return element is a pointer to allow chained modification of it.
func (r *Repository) Module(directory string) *Module {
	clean := filepath.Clean(directory)
	if r.modules == nil {
		r.modules = map[string]*Module{}
	}
	module, ok := r.modules[clean]
	if !ok {
		module = &Module{directory: clean, repo: r}
		r.modules[clean] = module
	}
	return module
}
