#!/bin/sh
# Code generated by kickr; DO NOT EDIT.

base_branch=
if [ -n "$GITHUB_BASE_REF" ]; then
  base_branch=origin/$GITHUB_BASE_REF
elif [ -n "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" ]; then
  base_branch="origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
else
  base_branch=HEAD~1
fi

type="(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)"
scope="(\(.+\))?"
conventionalcommit="^${type}${scope}(!)?:\s.+$"

echo "validating commits againts $base_branch"

errors=0
# shellcheck disable=SC2066
for commit in "$(git log --pretty=format:%s "${base_branch}..HEAD")"; do
  echo "validating '$commit' with conventional commits specification"
  if ! echo "$commit" | grep -qP "$conventionalcommit"; then
    errors=$((errors+1))
  fi
done

if [ "$errors" -ne 0 ]; then
  echo "invalid commits present between $base_branch and HEAD"
else
  echo "all commits are valid"
fi
