# Code generated by kickr; DO NOT EDIT.

APP_VERSION ?= v0.0.0

.PHONY: build
build:
	@hugo --gc --minify --destination dist --logLevel debug

.PHONY: serve
serve:
	@hugo server --disableFastRender --destination dist --logLevel debug

.PHONY: production
production: build
	@python3 -m http.server --directory dist
